apiVersion: apps/v1 
kind: Deployment
metadata:
  name: calico-kube-controllers
  namespace: kube-system
  labels:
    k8s-app: calico-kube-controllers
spec:
  # Only a single instance of the this pod should be
  # active at a time.  Since this pod is run as a Deployment,
  # Kubernetes will ensure the pod is recreated in case of failure,
  # removing the need for passive backups.
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-kube-controllers
      namespace: kube-system
      labels:
        k8s-app: calico-kube-controllers
    spec:
      hostNetwork: true
      serviceAccountName: calico-kube-controllers 
      containers:
        - name: calico-kube-controllers
          # Make sure to pin this to your desired version.
          image: calico/kube-controllers:latest-amd64
          env:
            # Configure the location of your etcd cluster.
            - name: ENABLED_CONTROLLERS
              value: routereflector
            - name: ETCD_ENDPOINTS
              value: "http://127.0.0.1:2379"
